### PR TITLE
fix: Pass along model version in GenerateContentResponse

### PR DESCRIPTION
**Pull request by Annhiluc**
## Description of the change
Pass along model version in GenerateContentResponse.

- Ran python docs/build_docs.py to update documentation.
- Ran pytest with no failures.

## Motivation
b/378140421

## Type of change
Bug fix

## Checklist

- [x] I have performed a self-review of my code.
- [x] I have added detailed comments to my code where applicable.
- [x] I have verified that my change does not break existing code.
- [x] My PR is based on the latest changes of the main branch (if unsure, please run `git pull --rebase upstream main`).
- [x] I am familiar with the [Google Style Guide](https://google.github.io/styleguide/) for the language I have coded in.
- [x] I have read through the [Contributing Guide](https://github.com/google/generative-ai-python/blob/main/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://cla.developers.google.com/about).

### CODE REVIEW

**Review by MarkDaoust — CHANGES_REQUESTED** [review]
Hi, thanks for the PR. Could you revert the generated docs? We'll refresh those with the next release.

**Review by MarkDaoust — CHANGES_REQUESTED** [review]
Oh, interesting. Tests are failing because the generated client library doesn't have that attribute. So this needs a new release of the client lib before we can merge.

**Comment by Annhiluc** [comment]
Thanks Mark for the review! Reverted docs.

> Tests are failing because the generated client library doesn't have that attribute.

To clarify, did I miss adding the `model_version` somewhere or has the client library already added this attribute and it hasn't been released yet? How can I check on the release of the client lib?

**Comment by MarkDaoust** [comment]
I need to release a new version and update the dependancies in setup.py.

cl/693090666

**Review by MarkDaoust — APPROVED** [review]

**Pull request merged**
